### ISSUE TITLE
B站推送异常

### ISSUE THREAD

**Issue by 8852690** [ikenxuan/kkkkkk-10086#17]
环境: 喵崽最新版, Node 18.20.2, b站已扫码登陆, 插件最新版本
![5f8a317e012a748c9401e53738ecdb6b](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/89b2e125-1bda-4d05-ab8d-5a65ab152ede)

**Comment by ikenxuan** [comment]
> 返回的data是
> ```
> {
>     "code": -352,
>     "message": "-352",
>     "ttl": 1
> }
> ```
> 似乎是风控了?

up的UID看看

**Comment by 8852690** [comment]
> > 返回的data是
> > ```
> > {
> >     "code": -352,
> >     "message": "-352",
> >     "ttl": 1
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 似乎是风控了?
> 
> up的UID看看

https://space.bilibili.com/10833955, 这里的uid应该是10833955? 我也换过其他的uid, 也会出现一样的问题.

**Comment by ikenxuan** [comment]
> > > 返回的data是
> > > ```
> > > {
> > >     "code": -352,
> > >     "message": "-352",
> > >     "ttl": 1
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 似乎是风控了?
> > 
> > 
> > up的UID看看
> 
> https://space.bilibili.com/10833955, 这里的uid应该是10833955? 我也换过其他的uid, 也会出现一样的问题.

设置B站推送的命令是 [#设置B站推送10833955]
检查config.json里面是否有相似内容：
```
{
      "host_mid": "10833955",
      "group_id": [
        123456789
      ],
      "remark": "安雅超级凶"
}
 ```

**Comment by 8852690** [comment]
![image](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/56b803d1-870c-4c3f-8a17-f02bfec8df4b)
是有的

**Comment by ikenxuan** [comment]
> ![image](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/56b803d1-870c-4c3f-8a17-f02bfec8df4b)
> 是有的, 另外, 我刚直接在服务器上访问这个space的地址是可以访问的, 可以排除说连不上bilibili的问题, 会不会是header里面少了什么?

可能是ck问题，我没法复现你的问题

**Comment by 8852690** [comment]
> > ![image](https://private-user-images.githubusercontent.com/59615518/330871399-56b803d1-870c-4c3f-8a17-f02bfec8df4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjY4OTUsIm5iZiI6MTcxNTgyNjU5NSwicGF0aCI6Ii81OTYxNTUxOC8zMzA4NzEzOTktNTZiODAzZDEtODcwYy00YzNmLThhMTctZjAyYmZlYzhkZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMjk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWNkOTBhMzVmNDgzNDdlOGQwNDU2YWM0ZDQ2ZWRiN2ZjMDUzYzI0ODlkYjgyZjhkMTI4YzIyNDcxNzBjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2B-etTu7hlNLN0MGTYNHnBVaVko8itjscc3mLuxKpcA)
> > 是有的, 另外, 我刚直接在服务器上访问这个space的地址是可以访问的, 可以排除说连不上bilibili的问题, 会不会是header里面少了什么?
> 
> 可能是ck问题，我没法复现你的问题。 你可以试着换一个UA试试看
> 
> https://github.com/ikenxuan/kkkkkk-10086/blob/a37acc87a5d7b129cdaea8fa303017044fd61ce5/model/global/base.js#L11

我刚尝试使用手动获取CK填入, 发现可以获取到data, 应该是扫码登陆获取ck缺少了什么.

**Comment by ikenxuan** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/59615518/330871399-56b803d1-870c-4c3f-8a17-f02bfec8df4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjY4OTUsIm5iZiI6MTcxNTgyNjU5NSwicGF0aCI6Ii81OTYxNTUxOC8zMzA4NzEzOTktNTZiODAzZDEtODcwYy00YzNmLThhMTctZjAyYmZlYzhkZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMjk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWNkOTBhMzVmNDgzNDdlOGQwNDU2YWM0ZDQ2ZWRiN2ZjMDUzYzI0ODlkYjgyZjhkMTI4YzIyNDcxNzBjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2B-etTu7hlNLN0MGTYNHnBVaVko8itjscc3mLuxKpcA)
> > > 是有的, 另外, 我刚直接在服务器上访问这个space的地址是可以访问的, 可以排除说连不上bilibili的问题, 会不会是header里面少了什么?
> > 
> > 
> > 可能是ck问题，我没法复现你的问题。 你可以试着换一个UA试试看
> > https://github.com/ikenxuan/kkkkkk-10086/blob/a37acc87a5d7b129cdaea8fa303017044fd61ce5/model/global/base.js#L11
> 
> 我刚尝试使用手动获取CK填入, 发现可以获取到data, 应该是扫码登陆获取ck缺少了什么.

扫码登录的日志看看

**Comment by 8852690** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/59615518/330871399-56b803d1-870c-4c3f-8a17-f02bfec8df4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjY4OTUsIm5iZiI6MTcxNTgyNjU5NSwicGF0aCI6Ii81OTYxNTUxOC8zMzA4NzEzOTktNTZiODAzZDEtODcwYy00YzNmLThhMTctZjAyYmZlYzhkZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMjk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWNkOTBhMzVmNDgzNDdlOGQwNDU2YWM0ZDQ2ZWRiN2ZjMDUzYzI0ODlkYjgyZjhkMTI4YzIyNDcxNzBjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2B-etTu7hlNLN0MGTYNHnBVaVko8itjscc3mLuxKpcA)
> > > > 是有的, 另外, 我刚直接在服务器上访问这个space的地址是可以访问的, 可以排除说连不上bilibili的问题, 会不会是header里面少了什么?
> > > 
> > > 
> > > 可能是ck问题，我没法复现你的问题。 你可以试着换一个UA试试看
> > > https://github.com/ikenxuan/kkkkkk-10086/blob/a37acc87a5d7b129cdaea8fa303017044fd61ce5/model/global/base.js#L11
> > 
> > 
> > 我刚尝试使用手动获取CK填入, 发现可以获取到data, 应该是扫码登陆获取ck缺少了什么.
> 
> 扫码登录的日志看看

![image](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/447f3a80-29c2-4bc8-b0aa-885bcc9d6085)
看起来这部分日志没有什么问题.

**Comment by 8852690** [comment]
![image](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/650f525e-8ddb-454f-ab64-83d4d458b62d)
不过扫码登陆后获取到的ck很奇怪, 是这个格式的, 跟手动获取差异很大

**Comment by 8852690** [comment]
![image](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/14ba75c4-e919-473c-ac17-8de0bf1b6465)
不过扫码登陆后的ck很奇怪, 是这样的格式

**Comment by ikenxuan** [comment]
> 不过扫码登陆后的ck很奇怪, 是这样的格式
> 第一次获取到的ck:
> ![image](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/5032aa10-9efb-474b-b4d7-89c7fba813ad)
> 
> 第二次获取到的ck:
> ![image](https://github.com/ikenxuan/kkkkkk-10086/assets/59615518/14ba75c4-e919-473c-ac17-8de0bf1b6465)

加群反馈帕，我也是喵崽目前还没遇到你这种情况

**Comment by 8852690** [comment]
> > 不过扫码登陆后的ck很奇怪, 是这样的格式
> > 第一次获取到的ck:
> > ![image](https://private-user-images.githubusercontent.com/59615518/331042769-5032aa10-9efb-474b-b4d7-89c7fba813ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDU4ODUsIm5iZiI6MTcxNTg0NTU4NSwicGF0aCI6Ii81OTYxNTUxOC8zMzEwNDI3NjktNTAzMmFhMTAtOWVmYi00NzRiLWI0ZDctODljN2ZiYTgxM2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA3NDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTljMTJmMGMzNDhiZjU0MGZmMTkxZDdmOWMwMjdkMmE4N2NkNjlmYmEyYjg5ZTNiNzcyOWJmMTZiZDA3ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RL8OcmYc_LWIj0-gPyNqiNJSbHvQUUNnT3PiCfvsNak)
> > 第二次获取到的ck:
> > ![image](https://private-user-images.githubusercontent.com/59615518/331042105-14ba75c4-e919-473c-ac17-8de0bf1b6465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDU4ODUsIm5iZiI6MTcxNTg0NTU4NSwicGF0aCI6Ii81OTYxNTUxOC8zMzEwNDIxMDUtMTRiYTc1YzQtZTkxOS00NzNjLWFjMTctOGRlMGJmMWI2NDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA3NDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ODMyYjJkYjBlMjhmNTBjZjcyNjUwOWZmZGIwNmEzYzhmZGE4NzdhYjIwZTFiZTYzNzk2NzJhODEwNTMwZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kKsFGYUj6zdLXqrgovC0F7WtibDuDpcuxELEIvllHU)
> 
> 加群反馈帕，我也是喵崽目前还没遇到你这种情况

Emmm...就在群里, 只是消息被刷上去了
