### ISSUE TITLE
希望加一个主动解析某个分享视频或者链接的功能 

### ISSUE THREAD

**Issue by wzwei1990** [ikenxuan/kkkkkk-10086#46]
### Please make sure of the following things

- [X] 我已经阅读了[文档](https://ikenxuan.github.io/kkkkkk-10086/)。
- [X] 我确定没有重复的issue或讨论。
- [X] 我确定这个功能没有实现。
- [X] 我相信这是一个合理和普遍的要求。

### 需求描述

自动解析有时候不需要 能否加一个主动解析某个分享视频或者链接的功能

### 实现思路

关闭自动解析也可以引用分享链接输入#解析来触发解析功能

**Comment by wzwei1990** [comment]
可以引用然后 解析吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月27日(周二) 下午5:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ikenxuan/kkkkkk-10086] 希望加一个主动解析某个分享视频或者链接的功能  (Issue #46)




 
Closed #46 as completed.

**Comment by ikenxuan** [comment]
https://github.com/ikenxuan/kkkkkk-10086/commit/8b47cab5d89e38dc05b444e39fbb1270d24c64e4 ，支持了

**Comment by wzwei1990** [comment]
好像没起作用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月27日(周二) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ikenxuan/kkkkkk-10086] 希望加一个主动解析某个分享视频或者链接的功能  (Issue #46)




 
8b47cab ，支持了

**Comment by ikenxuan** [comment]
需要关闭响应的解析开关才可使用

**Comment by wzwei1990** [comment]
我的是lagrangeOneBot 好像没起作用

**Comment by wzwei1990** [comment]
![80c960828e2f2c2b9a70e228f8568d4](https://github.com/user-attachments/assets/48cc8cc2-098b-4eeb-af89-6770cef7f934)
还是不起作用

**Comment by OduckO** [comment]
看看你引用的消息类型

**Comment by wzwei1990** [comment]
![image](https://github.com/user-attachments/assets/c04720d6-e221-4c3a-ba52-915e8b670bb2)

**Comment by OduckO** [comment]
你先试试引用文本消息，卡片消息暂时还未适配

**Comment by wzwei1990** [comment]
文本引用可以
