### ISSUE TITLE
[Bug?]: 更新后b站解析引用无效了

### ISSUE THREAD

**Issue by wzwei1990** [ikenxuan/kkkkkk-10086#62]
### 请确保以下事项

- [X] 我已经阅读了[文档](https://ikenxuan.github.io/kkkkkk-10086/)。
- [X] 我确定没有重复的issue或讨论。
- [X] 我确定是`kkkkkk-10086`的问题，而不是其他原因（例如网络，`依赖`或`操作`）。
- [X] 我确定这个问题在最新版本中没有被修复。

### 版本

1.5.0

### 问题描述

更新后b站解析引用无效了

### 配置

更新后b站解析引用无效了

### 操作步骤

更新后b站解析引用无效了

### 日志

更新后b站解析引用无效了

**Comment by ikenxuan** [comment]
没有日志不予受理
