### ISSUE TITLE
[Bug?]: B站解析视频内容优先与视频文件大小限制逻辑错误

### ISSUE THREAD

**Issue by liuyue-er** [ikenxuan/kkkkkk-10086#67]
### 请确保以下事项

- [X] 我已经阅读了[文档](https://ikenxuan.github.io/kkkkkk-10086/)。
- [X] 我确定没有重复的issue或讨论。
- [X] 我确定是`kkkkkk-10086`的问题，而不是其他原因（例如网络，`依赖`或`操作`）。
- [X] 我确定这个问题在最新版本中没有被修复。

### 版本

fb60baea8203bc687f498e9a8f728c3440ccd106

### 问题描述

B站解析视频内容优先功能选择为开启之后，应当让最低分辨率的视频大小与视频文件大小限制做对比，而不是最高的。例如，我将一个4k视频大小为150mb，360p分辨率为10mb的视频链接发出，开启内容优先后，解析的视频分辨率为360p，文件大小限制设置为100，会提示视频文件太大了，还是去B站看吧。正常逻辑这个视频应该允许发出

### 配置

filelimit: 100

videopriority: true

### 操作步骤

![Image_1727770150099](https://github.com/user-attachments/assets/08d2f828-626b-4551-9aa0-253a4150216c)

### 日志

[MiaoYz][16:08:49.117][INFO] recv from: [Group: 小白测试沙箱(你干嘛~哎哟~), Member: 流月e(你干嘛~哎哟~)] 【尬聊！无闪光真的适合实装吗？-哔哩哔哩】 https://b23.tv/1viwDAP                               [MiaoYz][16:08:49.182][INFO] [kkkkkk-10086-视频功能][bilib][小白 测试沙箱(流月e)] 【尬聊！无闪光真的适合实装吗？-哔哩哔哩】 https://b23.tv/1viwDAP                                                 [MiaoYz][16:08:51.268][INFO] succeed to send: [Group(你干嘛~哎哟~)] 检测到B站链接，开始解析                                          [MiaoYz][16:08:51.665][INFO] succeed to send: [Group(你干嘛~哎哟~)] [图片]                                                           # 标题: 尬聊！无闪光真的适合实装吗？                                                                                              作者: 莫娜摸鱼专用                                               播放量: 6.5万,    弹幕: 107                                      点赞: 3109,    投币: 49                                          转发: 20,    收藏: 146                                           [MiaoYz][16:08:55.557][MARK] [图片生成][kkkkkk-10086/bilibili/bilicomment/][1/1] 567.72KB                                         [MiaoYz][16:08:56.651][INFO] succeed to send: [Group(你干嘛~哎哟~)] [图片]                                                           [MiaoYz][16:08:56.917][INFO] succeed to send: [Group(你干嘛~哎哟~)] [回复@流月e]视频太大了，还是去B站看吧~                           [MiaoYz][16:08:56.921][MARK] [kkkkkk-10086-视频功能][bilib] 【尬 聊！无闪光真的适合实装吗？-哔哩哔哩】 https://b23.tv/1viwDAP 处理完成 7739ms

**Comment by shijinn520** [comment]
@liuyue-er 你好

**Comment by liuyue-er** [comment]
@shijinn520 你干嘛，哎呦~
